reference/employer/openapi.yaml

https://tryfinch.halp.com/tickets/1631
I searched for "type: 'regular'" and didn't see any interesting hits. The adapter returnr `regular_payroll` either from a hardcoded value or from the [enum](https://github.com/Finch-API/api-server/blob/master/lib/model.js#L117-L121).
Changing the return value of any of the adapters wouldn't be the right fix as that introduces a breaking change.

fix(docs): update pay statement type to regular_payroll

---

docs/Development-Guides/Providers.md
docs/Product-Guides/Assisted-Connect-Flow.md

Based on feedback from customer meetings and [#3003](https://tryfinch.halp.com/tickets/3003).
- Added info for both Read + Benefits. Linked Assisted Connect doc to learn more
- Explained limitation of Assisted Benefits
- Separated providers between API vs Assisted
- Brought all API providers to the top for better readability and convenience. Thought is everyone uses API providers and most won't use Assisted

Update Providers page with legend and better formatting

---

reference/employer/openapi.yaml

Add `401k_loan`  that have been used in api-server and fixed a bug for company city description
- reflect on api doc to show developers what options of benefit/deduction type we will return
- https://github.com/Finch-API/api-server/blob/master/adapters/insperity/utils.js#L273

feat(benefitType): add new benefit type that have been used in api-server

---

reference/employer/openapi.yaml

Document the `class_code` field as returned by the /employer/employment endpoint.
I've been able to confirm this functionality in prod for:
* ADP Run ✅
* ADP WFN ✅
* Paycom ✅
* Gusto ✅
* Sandbox (WIP will add it to some of the individuals for `largeco`)
---------------------------------------
Won't do until requested by the developer:
* QBO (still in dev)
* Paychex (still in dev)
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1202482547603202

feat: Document the `class_code` field as returned by the /employer/employment endpoint.

---

docs/3-Quickstart.md

The before text was talking about base64 encoding for HTTP Basic Auth despite the curl request no longer doing this. Replaced this with a block of text better explaining.

fix: no longer mention base64 in regards to the auth code for access token exchange

---

docs/Development-Guides/Providers.md

Following the Adapter release checklist: `**Engineering** - Update Providers on [Finch API doc]`

chore: move Sapling from Assisted to Automated

---

docs/Product-Guides/Benefits-API.md

The "Benefits API" page in our documentation contained incorrectly truncated links to our Benefits endpoints. This PR corrects the truncated links to their correct versions.

Update Benefits API documentation links

---

docs/Product-Guides/Benefits-API.md

Our Benefits API documentation had used both the phrase "currently not supported" and also the phrase "not currently supported". Based on the idea that customers would be looking for "is" or "is not" during questions about support, I recommend "not currently supported".

Small grammar nitpick for Benefits API

---

reference/employer/openapi.yaml

Example did not have a `type` field under `employee_deduction`, but the specification says that field should exist there.

Update Pay Statement example with employee deduction type

---

docs/Product-Guides/Benefits-API.md
reference/employer/openapi.yaml

Currently our Benefits endpoints do not specify whether they work for Automated or Assisted Benefits providers. While we do now have a separate documentation page specifying that Benefits endpoints should return errors if they are used incorrectly, it is important for the endpoint specifications themselves to say that they are or are not available for use depending on the type of provider.
This PR adds one of the following two strings to each Benefits endpoint as appropriate:
- "Availability: Automated and Assisted Benefits providers"
- "Availability: Automated providers only"

Add availability description to Benefits endpoints

---

package.json

Add package.json to export openapi spec as library
We want to use our openapi spec as the source of truth for server side response validation. This allows us to build the api spec as an npm package for api server to use

Add package.json to export openapi spec as library

---

docs/Integrating-with-Finch/Integrate-Finch-Connect/Embed-Connect.md
reference/employer/openapi.yaml

typo brought to attention in SUPPORT-689
param name brought to attention in SUPPORT-665

fix a typo and change payrollProvider to payroll_provider in embed connect guide

---

reference/employer/openapi.yaml

Change value of end_date in the employment endpoint to be potentially null
End dates can be null if the employee is active.

Allow end_date to be null

---

docs/3-Quickstart.md

Not having all the products listed confused many developers since they would immediately get an "unauthorized" when calling individual or pay data.

adding more products to the quickstart /authorize url

---

reference/employer/openapi.yaml

Add the missing `employer_contributions[].type` field into the Pay Statements API documentation example response

Add missing "type" key to Pay Statements response example

---

docs/Integrating-with-Finch/Integration Checklist.md

The Integration Checklist previously listed Slack and Halp under the "Support" section. This has confused at least one customer who did not have a Slack channel. In addition, we no longer use Halp except as a connection between Slack and Jira.
Updated the "Support" section to only mention Jira.

Remove mentions of Slack and Halp from Integration Checklist

---

docs/Development-Guides/Testing.md

Documentation for "Testing" previously had a curl command which used a JSON body containing a mix between creating a benefit and enrolling an individual. The corrected example is purely for creating a benefit.
Previous:
New:

Update Benefits curl command in Testing page

---

docs/Development-Guides/Providers.md

- Add "ADP Workforce Now" to Assisted list
- Mark "ADP Comprehensive Services" as pay-enabled
Before:
After:

Add ADP Workforce Now as Assisted connection

---

reference/employer/openapi.yaml

A developer thought they would need an access token to access this in [SUPPORT-2377](https://tryfinch.atlassian.net/browse/SUPPORT-2377)

set security for providers endpoint to none as it doesn't require auth

---

docs/Development-Guides/Providers.md

The "Last Updated" timestamp is accidentally "2022" instead of "2023".

Correct year on Providers page timestamp

---

docs/Development-Guides/Errors/Error-Types.md

for https://tryfinch.atlassian.net/browse/EN-822 adding documentation for the 502 error to indicate upstream provider issues

add 502 error

---

docs/Product-Guides/Automated-Connect-Flow.md
toc.json

I noticed a dead link in the docs referencing Response Times / Latency (see it on production [here](https://developer.tryfinch.com/docs/reference/a2c944f1041f6-automated-connect-flow#finch-connect-in-your-users-onboarding) under the section "Finch Connect in Your User's Onboarding") - it seems like there is no file corresponding to this link, so I went ahead and remove the reference to that and the uri in toc.json. 
Todo:

Remove response-times dead links

---

docs/Development-Guides/Providers.md

Updates three instances of `Benefits` to use `Write` instead, for clarity.

Changes Benefits headers to use Write

---

docs/Product-Guides/Assisted-Connect-Flow.md

Adds an example URL for launching Finch Connect with the manual flag, and slightly changes order of items in the section.

docs: Add URL example for launching Finch Connect with manual flag

---

docs/Integrating-with-Finch/Integrate-Finch-Connect/Embed-Connect.md

With [react-finch-connect](https://www.npmjs.com/package/react-finch-connect) being deprecated in favour of [react-connect](https://www.npmjs.com/package/@tryfinch/react-connect) SDK, we should update our docs accordingly.

chore(react-connect): Update react-connect urls pointing to deprecated repo [EN-2893]

---

reference/employer/openapi.yaml

fixed nullability on our schema for dob here : https://github.com/Finch-API/finch-openapi/pull/25 - figured it'd be worth updating our docs  - havent verified this looks ok on the render (we use `anyOf` in our schema so trying `nullable` here to see if it looks better),  just wanted to open a pr to get visibility

employer/individual: communicate dob might be null

---

docs/Integrating-with-Finch/Integrate-Finch-Connect/Embed-Connect.md

Updates the Finch Connect React embedded SDK documentation to include the newly added state parameter. Code updates taken from Aren's updates the the example here: https://github.com/Finch-API/react-connect/pull/59

Add state param example to embedded React SDK docs

---

reference/employer/openapi.yaml

Clarifies that the rate limit on the refresh endpoint is 1 request per hour per connection
This has caused confusion for at least 1 customer (Pulley)

chore: Clarifies refresh rate limit of 1 req/hour/cxn

---

.spectral.mjs
docs/Development-Guides/Providers.md

What changed:
- Update docs to show Benefits are not supported for PrismHR white labels (list below) 
- Confirmed through various sources that, since PrismHR is a PEO, they completely own making changes to employee deductions. Finch would not be able to process assisted benefits requests
[Sequoia One](https://seq.prismhr.com/seq/auth/#/login?lang=en)
[Amplify HR](https://whr.prismhr.com/whr.amp/)
[C2](https://c2p.prismhr.com/)
[Creative Business Resources (CBR)](https://cbr.prismhr.com/cbr/?) 
[Cognos HR](https://cog.prismhr.com/cog/)
[Empower HR](https://epw.prismhr.com/epw/?)
[Engage PEO](https://manager.engagepeo.com/phr/dbweb.asp?dbcgm=1)
[Extensis HR](https://exg.prismhr.com/exg/)
[G&A Partners](https://gna.prismhr.com/gna/?)
[Infiniti HR](https://inf.prismhr.com/inf.hsg/?)
[Prestige …

update docs to show assisted benefits not supported for prismHR white-labels

---

docs/Development-Guides/Versioning.md
docs/Integrating-with-Finch/Integrate-the-Finch-API.md

Adds a link to the version page on the integration page and adds a note about the date being old because we're good about not making breaking changes

Notes about version timing

---

reference/employer/openapi.yaml

replace another reference to /meta within the create-benefit doc page

Benefit-create: replace `/meta` reference with `/provider` reference 

---

docs/Development-Guides/Field-Support/Benefits-Support.md

- Update docs to show 401k Loans are supported (Paychex)
- Update docs to show 50+ catch-up is supported for 401k and 401k Roth (Paychex) 
- Update docs to show 401k Loans are supported (Paycom)
- Update docs to show Roth 401k catch-ups are supported (Quickbooks)

Modified docs/Development-Guides/Field-Support/Benefits-Support.md

---

docs/Development-Guides/SDKs.md
toc.json

Add page for SDKs. Pending SDK testing
Inspiration:
https://stripe.com/docs/libraries
https://plaid.com/docs/api/libraries/
https://docs.merge.dev/sdk/
https://workos.com/docs/sdks

add SDK documentation

---

reference/employer/openapi.yaml

Updated /enroll docs to make the `annual_contribution_limit` field nullable. Also updates some formatting

Modified openapi annual contribution limit nullable

---

reference/management/openapi.yaml

- Add client type and connection type to openAPI spec
`"client_type": "production" | "development" | "sandbox"`: the type of application associated with this token. equivalent to application.status
`"connection_type": "provider" | "finch"`: the type of connection associated with this token. `provider` = external, `finch` = finch generated

feat: Add client type and connection type to `/introspect`

---

reference/employer/openapi.yaml

Re-adding the UnenrollIndividuals schema that was mistakenly taken out.

fix(benefits): Add UnenrollIndividuals schema back in
