Finch-API/finch-docs

docs/ Finch API/Providers.md
just adding new providers to documentation. wanted you to review first to make sure nothing's wrong, will assign to alex/sam going forward!
=> adding new providers to documentation

docs/Employer/5-Employment.md
https://app.asana.com/0/1200417628030013/1200422576069053
=> Add effective_date

docs/Employer/5-Employment.md
https://app.asana.com/0/1200456064971560/1200481559623458
https://github.com/Finch-API/api-server/pull/422
=> Add income_history

docs/ Finch API/4 - Authorization.md
Derived from customer feedback.
=> docs: list products explicitly

docs/Employer/7-Pay-Statement.md
We actually validate this as a number in our code. This can be fractional, depending on the system e.g. 86.666667
=> fix: total hours to number

reference/employer/openapi.yaml
view rendered docs at https://developer.tryfinch.com/docs/reference/branches/benefits/reference/employer/openapi.yaml
see [PRD](https://www.notion.so/tryfinch/PRD-Benefits-b5e63103cfff43729cc2a942ce0792e0) for endpoints
=> feat: add benefits openapi endpoints

docs/Employer/7-Pay-Statement.md
related PR for implementation: https://github.com/Finch-API/api-server/pull/744
=> feat(pay-statements): add earnings hours

docs/Getting Started/A-Providers.md
BBCS Payroll, Nextep, PayNorthwest
=> adding 3 providers to documentation

reference/employer/openapi.yaml
organizes endpoints into categories
Also re-adds deprecated deductions docs
=> docs: separate endpoints into categories

reference/employer/openapi.yaml
=> Add quarterly

reference/employer/openapi.yaml
=> remove contributions/deductions from /benefits example

docs/Development-Guides/Headers.md
https://www.notion.so/tryfinch/PRD-Asynchronous-Request-Serving-c9bc4cb8754a4f3996aef69d0a3c2a16#509aa61c597d420bba2ded779361f93d
=> update headers section for async req phase 1

reference/employer/openapi.yaml
addressing comment: https://github.com/Finch-API/finch-docs/pull/72#discussion_r903903790
=> fix: remove errant apostrophe

reference/employer/openapi.yaml
Adding 'Run in Postman' link for our API Reference collection
[![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/21027137-08db0929-883d-4094-a9ce-dbf5a9bee4a4?action=collection%2Ffork&collection-url=entityId%3D21027137-08db0929-883d-4094-a9ce-dbf5a9bee4a4%26entityType%3Dcollection%26workspaceId%3D1edf19bc-e0a8-41e9-ac55-481a4b50790b)
=> Adding 'Run in Postman' button

docs/Development-Guides/Compatibility.md
Add Personio compatibility for company, directory, individual and employment endpoints
=> feat: Add Personio compatibility to docs

docs/Development-Guides/Providers.md
Add Sage HR to the Providers table in Finch API Docs
=> feat(sage_hr): add to finch docs

docs/Development-Guides/Providers.md
Horizons, Multiplier, odoo, ProSoftware, Southeast Personnel Leasing
=> Add 5 new ACF providers to docs

docs/Integrating-with-Finch/Integrate-Finch-Connect/Embed-Connect.md
Add docs for the upcoming JS SDK
=> feat: update embedding connect docs for js sdk

reference/employer/openapi.yaml
Many of the fields in our schema are nullable in practice but not in the spec in this repo
=> fix(openapi): make fields nullable

docs/Development-Guides/Providers.md
=> Update docs for new manual FC providers ADP comp and Solution Services

docs/Development-Guides/Providers.md
Add Wave to https://developer.tryfinch.com/docs/reference/96f5be9e0ec1a-providers
=> feat (wave): add Wave adapter to docs

docs/Development-Guides/Providers.md
I also removed Sage 50 Quantum Accounting and Sage 50 US Edition accounting from the docs
=> add paytime, deltek to dev docs

docs/Integrating-with-Finch/Integrate-Finch-Connect/Embed-Connect.md, docs/Integrating-with-Finch/Integrate-Finch-Connect/Redirect-to-Connect.md
Developer reported typo in https://tryfinch.atlassian.net/browse/SUPPORT-1042
=> Update param clientId -> client_id for getting a token in "Embedding Connect" and "Redirect to Connect" pages

docs/Development-Guides/Compatibility.md
switching to API token compatibility for rippling
=> docs: new rippling compatibility for API

docs/Development-Guides/Providers.md
remove adp-wfn from developer doc due to adp wfn outage
=> EN-1232: remove adp-wfn from developer doc

docs/Development-Guides/Errors/Error-Handling.md, docs/Development-Guides/Errors/Error-Types.md
corresponding doc changes for https://github.com/Finch-API/api-server/pull/3630
=> fix: update error codes in batch to match unbatched format

docs/Development-Guides/Providers.md
This reverts commit f88464c0bd1570dcdd92ad6b8a8514996ff499bc.
=> Revert "Modified docs/Development-Guides/Providers.md"

reference/employer/openapi.yaml
=> Correct "deduction" to "earning" in Pay Statement description

docs/Development-Guides/Providers.md
=> Return Trinet to Assisted Benefits

.stoplight/styleguide.json, docs/Development-Guides/Errors/Error-Types.md
=> fix: rate limit error handling formatting

docs/Integrating-with-Finch/How Finch Works.md
Updates the How Finch Works guide utilizing Tyler's expanded V2 content.
=> docs: Updates How Finch Works content to V2

docs/Development-Guides/Providers.md
=> Add C2 as new ACF provider in Finch docs

docs/Integrating-with-Finch/Integrate-Finch-Connect/Embed-Connect.md
- Changes instances of `Connect` to `Finch Connect`
- For React and JS SDK tabs, adds in expanded guide content.
- Minor structure changes
=> docs: Updates Embed Finch Connect guide to include detailed SDK guides

docs/Development-Guides/Field-Support/Benefits-Support.md
Add Supported features for 401k and 401k roth for Paychex
=> Add Supported features for 401k and 401k roth for Paychex

docs/Development-Guides/Providers.md
=> Add North Bay Payroll to docs

docs/Development-Guides/Providers.md
Update provider documentation to include costaff hr, a prism hr whitelabel at penelope's request
=> Update Providers.md to add CoStaff HR

reference/employer/openapi.yaml
[Jira ticket](https://tryfinch.atlassian.net/browse/EN-3456?atlOrigin=eyJpIjoiYjJhZTQ1YzEzZjJhNDBlOWJiM2JjNjBlNDUxNTYxZGEiLCJwIjoiaiJ9)
=> Update meta deprecated with link to `/providers`

docs/Development-Guides/Providers.md
Payentry was missing from docs and needed to be added. Confirmed that it is listed in FC correctly.
=> Modified docs/Development-Guides/Providers.md

docs/Product-Guides/Benefits-API.md
Removed one-time post-tax deduction messaging in Benefits API page
=> Modified docs/Product-Guides/Benefits-API.md - removed Benefits API messaging

reference/employer/openapi.yaml
Adding object and array to employment custom fields schema
=> Adding object type to employment custom fields schema

docs/Development-Guides/Providers.md
=> Made Paycom as Assisted in Providers

reference/management/openapi.yaml
adjusting type to data_sync_all as it was previously data-sync-all which is incorrect
=> adjusting type to data_sync_all

reference/employer/openapi.yaml
Update openapi.yaml /individual endpoint with encrypted_ssn
=> feat: Update openapi.yaml with encrypted_ssn

reference/employer/openapi.yaml
=> fix(benefits): Fix get enrollment example

docs/Development-Guides/Errors/Error-Types.md
We use this error for some failed validations on the benefits endpoints
https://tryfinch.atlassian.net/browse/EN-4836
=> add bad request error to error types

reference/employer/openapi.yaml
Updates to the latest openapi spec from https://github.com/Finch-API/finch-openapi
~Is this ok to publish? Seems like this hasn't been updated in a while. I had a small change I wanted to introduce but seems like a lot in this spec file has changed~
finch-openapi PR
https://github.com/Finch-API/finch-openapi/pull/49
=> Update openapi spec
